### ISSUE TITLE
1.9.2 Error

### ISSUE THREAD

**Issue by JustOneMoreBlock** [mstiles92/BookRules#24]
http://pastebin.com/raw/R1M9w345

Getting on the latest 1.9.2.

Plugin still works. However, just displays an error in console.

**Comment by mstiles92** [comment]
Ok, thanks for reporting this. I will take a look at it when I get a chance. Looks like it is probably only affecting the MCStats reporting.

Are you running CraftBukkit or Spigot?

**Comment by mstiles92** [comment]
Ok, I updated the dependencies for the project (including MCStats) and I have a dev build available here: https://mstiles92.com/jenkins/job/BookRules-Dev/21/artifact/target/BookRules-2.1.1.jar

I did not get the error you reported with this new build, but don't have time to fully test it, so let me know if you run into any issues. If not, I'll release this build as 2.1.2 on BukkitDev.

**Comment by JustOneMoreBlock** [comment]
Yeah, no more errors and it's working fine.
