### ISSUE TITLE
NullPointerException on PlayerJoinEvent

### ISSUE THREAD

**Issue by jounas** [mstiles92/BookRules#25]
I keep getting this error with 1.9.2 and now with just built 1.8.4 Spigot.

It HAS worked at least with some version at some point, at least for part of the cases, as players.yml is showing at least some entries.

http://pastebin.com/yew8rnmP

**Comment by mstiles92** [comment]
Thanks for reporting this, I think I see the issue here. I am guessing you have the plugin's update-checking disabled? If so, re-enabling that temporarily should fix this error for now. I will take a closer look at it this weekend and try to get a fix released.

**Comment by mstiles92** [comment]
Fix has been published to BukkitDev. It will be available here once approved: http://dev.bukkit.org/bukkit-plugins/bookrules/files/12-v2-1-3/
